[CiradDataverse]
title = "Newly published Datasets from Cirad Dataverse"
url = "https://dataverse.cirad.fr/dataverse/CIRAD"
entrySelector = "#resultsTable tbody tr td div‧datasetResult‧clearfix"
titleSelector = "div‧card-title-icon-block a span"
linkSelector = "div‧card-title-icon-block a"

[LaGazetteCafeCycliste]
title = "La Gazette de café du cycliste"
url = "https://www.cafeducycliste.com/la-gazette/"
entrySelector = "#gazette-container‧post-list div‧item-box"
titleSelector = "p strong"
linkSelector = "h2 a"
