[default]
waitUntil = "load"
timeout = 120

[CiradDataverse]
title = "Newly published Datasets from Cirad Dataverse"
url = "https://dataverse.cirad.fr/dataverse/CIRAD"
entrySelector = "#resultsTable tbody tr td"
titleSelector = ".datasetResult .card-title-icon-block a span"
linkSelector = ".datasetResult .card-title-icon-block a"

[LaGazetteCafeCycliste]
title = "La Gazette de café du cycliste"
url = "https://www.cafeducycliste.com/la-gazette/"
entrySelector = "#gazette-container .item-box"
titleSelector = "p strong"
linkSelector = "h2 a"

[gravelstoke]
title = "Gravel Cycling Gear Blog — Gravelstoke"
url = "https://www.gravelstoke.com/gravel-cycling-gear-blog"
entrySelector = ".BlogList .BlogList-item"
titleSelector = ".BlogList-item-title"
linkSelector = ".BlogList-item-excerpt a.BlogList-item-readmore"
